name: Nx Generate Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

env:
  GIT_USER_NAME: 'github-actions[bot]'
  GIT_USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'

concurrency:
  group: nx-g-workflow
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  push:
    name: Generate Nx Monorepo
    strategy:
      matrix:
        preset: [ angular-monorepo, nest ]
        bundler: [ esbuild ]
        unitTestRunner: [ jest, vitest, none ]
        e2eTestRunner: [ playwright, cypress, none ]
        exclude:
          - preset: nest
            unitTestRunner: vitest
          - preset: nest
            e2eTestRunner: playwright
          - preset: nest
            e2eTestRunner: cypress
        include:
          - name: client
            preset: angular-monorepo
          - name: server
            preset: nest
          - runner: angular
            preset: angular-monorepo
          - runner: nest
            preset: nest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Branch Step
        run: |
          BRANCH=${{ matrix.preset }}/${{ matrix.bundler }}-${{ matrix.unitTestRunner }}-${{ matrix.e2eTestRunner }}
          git fetch origin $BRANCH || true
          if git show-ref --verify --quiet refs/remotes/origin/$BRANCH; then
          git checkout $BRANCH
          git merge origin/$BRANCH
          else
          git checkout -b $BRANCH
          fi
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Setup Node Step
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get Nx Version Step
        id: nx_version
        run: |
          VERSION=$(npx -y create-nx-workspace@latest --version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git Step
        run: |
          git config user.name ${{ env.GIT_USER_NAME }}
          git config user.email ${{ env.GIT_USER_EMAIL }}

      - name: Remove Previous Version Step
        run: rm -rf ./workspace

      - name: Generate Next Version Step
        run: |
          npx -y create-nx-workspace@latest \
          --name=workspace \
          --preset=${{ matrix.preset }} \
          --bundler=${{ matrix.bundler }} \
          --interactive=false \
          --workspaceType=integrated \
          --appName=${{ matrix.name }} \
          --style=scss \
          --standaloneApi=true \
          --routing=true \
          --unitTestRunner=${{ matrix.unitTestRunner }} \
          --e2eTestRunner=${{ matrix.e2eTestRunner }} \
          --skipGit=false \
          --docker=false \
          --workspaces=false \
          --useProjectJson=true \
          --ci=skip

      - name: Generate Server Library Step
        if: matrix.runner == 'nest'
        run: |
          cd workspace && \
          npx -y nx@latest g @nx/${{ matrix.runner }}:lib libs/${{ matrix.name }}/core \
          --importPath=@workspace/${{ matrix.name }}-core \
          --name=${{ matrix.name }}-core \
          --linter=eslint \
          --unitTestRunner=${{ matrix.unitTestRunner }} \
          --useProjectJson=true 

      - name: Generate Client Library Step
        if: matrix.runner == 'angular'
        run: |
          cd workspace && \
          npx -y nx@latest g @nx/${{ matrix.runner }}:lib libs/${{ matrix.name }}/core \
          --importPath=@workspace/${{ matrix.name }}-core \
          --name=${{ matrix.name }}-core \
          --linter=eslint \
          --style=scss \
          --unitTestRunner=${{ matrix.unitTestRunner }}

      - name: Commit Changes Step
        id: git_commit
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore(${{ matrix.preset }}): create-nx-workspace@${{ steps.nx_version.outputs.version }}"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push Branch Step
        if: steps.git_commit.outputs.changes == 'true'
        run: git push origin ${{ env.BRANCH_NAME }}
