name: Orchestrate Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write

jobs:
  lint-test-build:
    name: Nx Angular-monorepo Workflow Job
    uses: ./.github/workflows/nx-angular-monorepo-workflow.yml
